version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-jobs}
      POSTGRES_USER: ${POSTGRES_USER:-jobs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jobs}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-jobs}:${POSTGRES_PASSWORD:-jobs}@db:5432/${POSTGRES_DB:-jobs}
      API_KEY: ${API_KEY:-dev123}
      LOCK_TTL_SECONDS: ${LOCK_TTL_SECONDS:-120}
    depends_on:
      - db
    volumes:
      - ./app:/app
    ports:
      - "7250:8000"

volumes:
  pgdata:
